export const loadStatuses = {
  LOADING: 'LOADING',
  NOT_LOADING: 'NOT_LOADING',
  LOAD_SUCCESS: 'LOAD_SUCCESS',
  LOAD_FAILED: 'LOAD_FAILED',
};

export const createStatuses = {
  CREATING: 'CREATING',
  NOT_CREATING: 'NOT_CREATING',
  CREATION_SUCCESS: 'CREATION_SUCCESS',
  CREATION_FAILED: 'CREATION_FAILED',
};
