export const loadStatuses = {
  LOADING: 'LOADING',
  NOT_LOADING: 'NOT_LOADING',
  LOAD_SUCCESS: 'LOAD_SUCCESS',
  LOAD_FAILED: 'LOAD_FAILED',
};

export const createStatuses = {
  CREATING: 'CREATING',
  NOT_CREATING: 'NOT_CREATING',
  CREATION_SUCCESS: 'CREATION_SUCCESS',
  CREATION_FAILED: 'CREATION_FAILED',
};

export const updateStatuses = {
  UPDATING: 'UPDATING',
  NOT_UPDATING: 'NOT_UPDATING',
  UPDATE_SUCCESS: 'UPDATE_SUCCESS',
  UPDATE_FAILED: 'UPDATE_FAILED',
};

export const deleteStatuses = {
  DELETING: 'CREATING',
  NOT_DELETING: 'NOT_CREATING',
  DELETION_SUCCESS: 'CREATION_SUCCESS',
  DELETION_FAILED: 'CREATION_FAILED',
};
