export const tKeys = {
  CANCEL: 'CANCEL',
  CREATE_EVENT: 'CREATE_EVENT',
  DESCRIPTION: 'DESCRIPTION',
  EVENTS: 'EVENTS',
  LOCATION: 'LOCATION',
  MAP: 'MAP',
  NAME: 'NAME',
  SAVE: 'SAVE',
  SEARCH: 'SEARCH',
};
